CREATE TABLE IF NOT EXISTS users(
id INTEGER PRIMARY KEY,
username TEXT UNIQUE,
quota INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sessions(
id INTEGER PRIMARY KEY,
username TEXT,
online INTEGER DEFAULT 0
);
