CREATE TABLE users(
id INTEGER PRIMARY KEY,
username TEXT UNIQUE,
quota INTEGER DEFAULT 0,
traffic INTEGER DEFAULT 0
);

CREATE TABLE sessions(
id INTEGER PRIMARY KEY,
username TEXT,
online INTEGER DEFAULT 0
);
