import fcntl
import grp
import json
import os
import re
import socket
import subprocess
import tempfile
import time
from pathlib import Path

from .settings import settings
from .validation import validate_password, validate_username

LOCK = Path("/run/lock/custom-panel-accounts.lock")
MANAGED_GROUP = "cpusers"
MARKER = "custom-panel-managed"
HOLD = "/usr/local/lib/custom-panel/panel-hold"
SSHD_CONFIG = "/etc/ssh/sshd_config_custom_panel"

def command(args, input_text=None, check=True, timeout=40):
    last = None
    for attempt in range(5):
        result = subprocess.run(
            args,
            input=input_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=timeout,
        )
        if result.returncode == 0 or not check:
            return result
        last = result
        message = ((result.stderr or "") + (result.stdout or "")).lower()
        if "cannot lock" not in message and "failure while writing" not in message:
            break
        time.sleep(0.5 + attempt)
    raise RuntimeError((last.stderr or last.stdout).strip() if last else "command failed")

def account_exists(username):
    return command(["getent", "passwd", username], check=False).returncode == 0

def account_lock():
    LOCK.parent.mkdir(parents=True, exist_ok=True)
    return LOCK.open("a+")

def upsert_user(username, password):
    username = validate_username(username)
    password = validate_password(password)
    with account_lock() as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        if not account_exists(username):
            command([
                "useradd", "-M", "-N", "-G", MANAGED_GROUP,
                "-c", MARKER, "-s", HOLD, username,
            ])
        else:
            command([
                "usermod", "-a", "-G", MANAGED_GROUP,
                "-c", MARKER, "-s", HOLD, username,
            ])
        command(["chpasswd"], f"{username}:{password}\n")
        command(["usermod", "-U", username], check=False)

def set_password(username, password):
    username = validate_username(username)
    password = validate_password(password)
    with account_lock() as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        if not account_exists(username):
            raise ValueError("کاربر لینوکس پیدا نشد.")
        command(["chpasswd"], f"{username}:{password}\n")

def pause_user(username):
    username = validate_username(username)
    with account_lock() as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        command(["usermod", "-L", username], check=False)
    command(["pkill", "-KILL", "-u", username], check=False)

def resume_user(username):
    username = validate_username(username)
    with account_lock() as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        command(["usermod", "-U", username], check=False)

def delete_user(username):
    username = validate_username(username)
    command(["pkill", "-KILL", "-u", username], check=False)
    with account_lock() as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        command(["userdel", "-r", username], check=False)

def render_sshd(mappings):
    lines = [
        "# Generated by Custom Panel. Do not edit.",
        "ListenAddress 127.0.0.1:2299",
    ]
    for item in mappings:
        lines.append(f"ListenAddress 127.0.0.1:{int(item['backend_port'])}")

    lines += [
        "Protocol 2",
        "HostKey /etc/ssh/ssh_host_ed25519_key",
        "HostKey /etc/ssh/ssh_host_rsa_key",
        "UsePAM yes",
        "PAMServiceName custom-panel-sshd",
        "PasswordAuthentication yes",
        "KbdInteractiveAuthentication no",
        "PubkeyAuthentication no",
        "PermitRootLogin no",
        "PermitEmptyPasswords no",
        f"AllowGroups {MANAGED_GROUP}",
        "AllowUsers __cp_disabled__",
        "X11Forwarding no",
        "AllowAgentForwarding no",
        "AllowTcpForwarding yes",
        "GatewayPorts no",
        "PermitTunnel no",
        "PermitTTY no",
        "PrintMotd no",
        "UseDNS no",
        "ClientAliveInterval 45",
        "ClientAliveCountMax 2",
        "MaxAuthTries 4",
        "LoginGraceTime 30",
        "PidFile /run/custom-panel-sshd.pid",
        "Subsystem sftp internal-sftp",
        f"ForceCommand {HOLD}",
    ]

    for item in mappings:
        username = validate_username(item["username"])
        port = int(item["backend_port"])
        lines += [
            "",
            f"Match LocalPort {port}",
            f"    AllowUsers {username}",
        ]
    return "\n".join(lines) + "\n"

def sync_backend(mappings):
    content = render_sshd(mappings)
    Path(SSHD_CONFIG).parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", delete=False, dir="/etc/ssh", prefix=".cp-sshd-") as tmp:
        tmp.write(content)
        temp_name = tmp.name
    try:
        os.chmod(temp_name, 0o600)
        command(["/usr/sbin/sshd", "-t", "-f", temp_name])
        os.replace(temp_name, SSHD_CONFIG)
        command(["systemctl", "reload-or-restart", "custom-panel-sshd.service"])
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass


def write_admin_credentials(username, password):
    username = validate_username(username)
    if len(password) < 10 or "\n" in password:
        raise ValueError("Invalid administrator password")
    path = Path("/etc/custom-panel/admin-credentials.txt")
    temp = path.with_suffix(".tmp")
    temp.write_text(f"Username: {username}\nPassword: {password}\n", encoding="utf-8")
    os.chmod(temp, 0o600)
    os.replace(temp, path)

def dispatch(payload):
    action = payload.get("action")
    if action == "user.upsert":
        upsert_user(payload["username"], payload["password"])
    elif action == "user.password":
        set_password(payload["username"], payload["password"])
    elif action == "user.pause":
        pause_user(payload["username"])
    elif action == "user.resume":
        resume_user(payload["username"])
    elif action == "user.delete":
        delete_user(payload["username"])
    elif action == "backend.sync":
        sync_backend(payload.get("mappings", []))
    elif action == "admin.credentials":
        write_admin_credentials(payload["username"], payload["password"])
    else:
        raise ValueError("Unknown helper action")
    return {"done": True}

def handle(conn):
    try:
        raw = b""
        while not raw.endswith(b"\n"):
            chunk = conn.recv(65536)
            if not chunk:
                break
            raw += chunk
        result = dispatch(json.loads(raw.decode()))
        response = {"ok": True, "result": result}
    except Exception as exc:
        response = {"ok": False, "error": str(exc)}
    conn.sendall((json.dumps(response, separators=(",", ":")) + "\n").encode())

def main():
    path = Path(settings.helper_socket)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.unlink(missing_ok=True)
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as server:
        server.bind(str(path))
        os.chmod(path, 0o660)
        os.chown(path, 0, grp.getgrnam("custompanel").gr_gid)
        server.listen(64)
        while True:
            conn, _ = server.accept()
            with conn:
                handle(conn)

if __name__ == "__main__":
    main()
